/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import Config.KoneksiDatabase;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class cariPasien extends javax.swing.JFrame {

    private DefaultTableModel tabmode;
    private final Connection conn = KoneksiDatabase.getConnection();
    public formpendaftaran daftar;
    private int selectedCol;
    rekammedis rekam;
    public Resep resep;

    /**
     * Creates new form cariPasien
     */
    public cariPasien() {
        initComponents();
        datatable();
        setupMouseListener();
    }

    private void setupMouseListener() {
        tpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpasienMouseClicked(evt);
            }

            private void tpasienMouseClicked(MouseEvent evt) {
                // Hapus baris ini:
                // throw new UnsupportedOperationException("Not supported yet.");

                // Tambahkan kode untuk handle klik jika diperlukan
                int selectedRow = tpasien.getSelectedRow();
                if (selectedRow != -1) {
                    // Lakukan sesuatu dengan baris yang dipilih
                    System.out.println("Row " + selectedRow + " selected");
                }
            }
        });
    }

    protected void datatable() {
        String[] Baris = {"ID Pasien", "Nama Pasien"};
        tabmode = new DefaultTableModel(null, Baris);
        tpasien.setModel(tabmode);

        String sql = "SELECT id_pasien, nama_pasien FROM pasien";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String idpas = hasil.getString("id_pasien");
                String namapas = hasil.getString("nama_pasien");

                String[] data = {idpas, namapas};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpasien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpasienMouseClicked(evt);
            }
        });
        tpasien.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tpasienCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tpasien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpasienMouseClicked
        // TODO add your handling code here:
try {
    int selectedRow = tpasien.getSelectedRow();

    if (selectedRow >= 0) {
        String idpas = tpasien.getValueAt(selectedRow, 0).toString();
        String namapas = tpasien.getValueAt(selectedRow, 1).toString();
        
        // Cek form mana yang memanggil
        if (daftar != null) {
            daftar.idpas = idpas;
            daftar.pasienTerpilih();
        } else if (rekam != null) {
            rekam.idpas = idpas;
            rekam.pasienTerpilih(); // panggil metode agar form rekam langsung di-update
        } else if (resep != null) {
            resep.idpas = idpas;
            resep.namapas = namapas;
            resep.pasienTerpilih();
        }
        
        dispose();
    }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
            dispose();
        }
    
    }//GEN-LAST:event_tpasienMouseClicked

    private void tpasienCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tpasienCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasienCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tpasien;
    // End of variables declaration//GEN-END:variables
}
