/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import Config.KoneksiDatabase;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class cariDokter1 extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private final Connection conn = KoneksiDatabase.getConnection();
   public formpoli polii;
    public pembayaran bayar;
    public Resep resep; // Tambahkan untuk form resep
    private JTable ttable;
    formpendaftaran daftar;
    public rekammedis rekam;

    
    public cariDokter1() {
        initComponents();
        datatable();
        setupMouseListener();
    }
    
    private void setupMouseListener() {
        ttabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelMouseClicked(evt);
            }
        });
    }
    
    protected void datatable(){
        String[] Baris = {"ID Dokter","Nama Dokter", "Poli"};
        tabmode = new DefaultTableModel(null, Baris);
        ttabel.setModel(tabmode);
        
        String sql = "SELECT id_dokter, nama_dokter, poli FROM dokter";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String id = hasil.getString("id_dokter");
                String nama = hasil.getString("nama_dokter");
                String npoli = hasil.getString("poli");
                
                String[] data = {id, nama, npoli};
                tabmode.addRow(data);
            }
        } catch (Exception e){ 
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ttabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ttabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ttabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ttabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ttabelAncestorAdded

    }//GEN-LAST:event_ttabelAncestorAdded

    private void ttabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttabelMouseClicked
        // TODO add your handling code here:
try {
    int selectedRow = ttabel.getSelectedRow();
    int selectedCol = ttabel.getSelectedColumn();

    if (selectedRow >= 0 && selectedCol == 0) {
        String id = ttabel.getValueAt(selectedRow, 0).toString();
        String nama = ttabel.getValueAt(selectedRow, 1).toString();
        String npoli = ttabel.getValueAt(selectedRow, 2).toString();
        
        // Cek form mana yang memanggil
        if (polii != null) {
            polii.id = id;
            polii.dokterTerpilih();
        } else if (bayar != null) {
            bayar.id = id;
            bayar.dokterTerpilih();
        } else if (resep != null) {
            resep.id = id;
            resep.nama = nama;
            resep.dokterTerpilih();
        } else if (daftar != null) {
            daftar.id = id;
            daftar.npoli = npoli;
            daftar.dokterTerpilih();
        } else if (rekam != null) {
            rekam.id = id;
            rekam.npoli = npoli;  // set npoli sesuai kebutuhan Anda
            rekam.dokterTerpilih(); // panggil metode agar form rekam langsung di-update
        }

        this.dispose();
    }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    
                                   
    }//GEN-LAST:event_ttabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariDokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariDokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariDokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariDokter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariDokter1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ttabel;
    // End of variables declaration//GEN-END:variables
}
