/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import Config.KoneksiDatabase;
import java.awt.Window;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


public class cariresep extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private final Connection conn = KoneksiDatabase.getConnection();
    private int selectedCol;
    public pembayaran bayar;
    
    /**
     * Creates new form cariPasien
     */
    public cariresep() {
        initComponents();
        // Panggil datatable() setelah initComponents()
        datatable();
        // Hapus setupMouseListener() karena sudah ada di initComponents()
    }

    protected void datatable() {
        String[] Baris = {"ID Resep"};
        tabmode = new DefaultTableModel(null, Baris);
        tresep.setModel(tabmode); // Set model ke tabel

        String sql = "SELECT id_resep1 FROM resep";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            // Debug: cek apakah ada data
            boolean hasData = false;
            while (hasil.next()) {
                hasData = true;
                String idres = hasil.getString("id_resep1");
                String[] data = {idres};
                tabmode.addRow(data);
                System.out.println("Data ditambahkan: " + idres); // Debug
            }
            
            if (!hasData) {
                System.out.println("Tidak ada data ditemukan di tabel resep");
            } else {
                System.out.println("Total baris: " + tabmode.getRowCount());
            }
            
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }
    }


    /**
     * Creates new form cariresep
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tresep = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tresep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tresep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresepMouseClicked(evt);
            }
        });
        tresep.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tresepInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tresep);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tresepInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tresepInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tresepInputMethodTextChanged

    private void tresepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresepMouseClicked
        // TODO add your handling code here:
try {
    int selectedRow = tresep.getSelectedRow();

    if (selectedRow >= 0) {
        String idResep = tresep.getValueAt(selectedRow, 0).toString();
        
        // Cek form mana yang memanggil
        if (bayar != null) {
            bayar.id = idResep;
            bayar.resepTerpilih();
        } 
        
        dispose();
    }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
            dispose();
        }
    
    }//GEN-LAST:event_tresepMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cariresep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cariresep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cariresep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cariresep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariresep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tresep;
    // End of variables declaration//GEN-END:variables
}
