/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import Apps.EncryptDecrypt;
import static Apps.EncryptDecrypt.decrypt;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {
    /**
     * Creates new form Dashboard
     */

private String jabatan = decrypt(SessionManager.getjabatan()); 
private String jenkel = decrypt(SessionManager.getjenkel());
    public Dashboard() {
        initComponents();
        setFullScreen();
        setUserNip(); 
        checkrole();
        revalidate();
        repaint();
  
    }
    private void checkrole(){
        if ("Kepala Puskesmas".equalsIgnoreCase(jabatan)) {
        manageuserdata.setVisible(true);
        manageuserdata.setIcon(resizeIcon("/Image/adminmanagement.png", 40, 40));
        manageuserdata.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        manageuserdata.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        }else{
            manageuserdata.setVisible(false);
        }
    
    }
    private ImageIcon resizeIcon(String path, int width, int height) {
    ImageIcon icon = new ImageIcon(getClass().getResource(path)); 
    Image img = icon.getImage(); // Mengambil objek Image dari ImageIcon
    Image resizedImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH); // Resize gambar
    return new ImageIcon(resizedImg); // Mengembalikan ImageIcon dengan ukuran baru
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        backgroundlogin1 = new Apps.backgrounddashboard();
        jPanel2 = new javax.swing.JPanel();
        manageuserdata = new javax.swing.JButton();
        btnpoli = new javax.swing.JButton();
        bdokter = new javax.swing.JButton();
        Button_obat = new javax.swing.JButton();
        Button_pasien = new javax.swing.JButton();
        btndaftar = new javax.swing.JButton();
        brekam = new javax.swing.JButton();
        bresep = new javax.swing.JButton();
        btnpembayaran = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo2 = new Apps.logo();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Puskesmas Kemuning");
        setName("framedashboard"); // NOI18N
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(11, 99, 162));

        manageuserdata.setBackground(new java.awt.Color(105, 183, 240));
        manageuserdata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageuserdata.setText("Manage User");
        manageuserdata.setBorderPainted(false);
        manageuserdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuserdataActionPerformed(evt);
            }
        });

        btnpoli.setBackground(new java.awt.Color(105, 183, 240));
        btnpoli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpoli.setText("Poli");
        btnpoli.setIcon(resizeIcon("/Image/poli.png", 50, 40));
        btnpoli.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        btnpoli.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        btnpoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpoliActionPerformed(evt);
            }
        });

        bdokter.setBackground(new java.awt.Color(105, 183, 240));
        bdokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdokter.setText("Dokter");
        bdokter.setIcon(resizeIcon("/Image/dokter.jpg", 40, 40));
        bdokter.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        bdokter.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        bdokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdokterActionPerformed(evt);
            }
        });

        Button_obat.setBackground(new java.awt.Color(105, 183, 240));
        Button_obat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_obat.setText("Obat");
        Button_obat.setIcon(resizeIcon("/Image/obat_icon.png", 40, 40));
        Button_obat.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        Button_obat.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        Button_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_obatActionPerformed(evt);
            }
        });

        Button_pasien.setBackground(new java.awt.Color(105, 183, 240));
        Button_pasien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_pasien.setText("Pasien");
        Button_pasien.setIcon(resizeIcon("/Image/pasien.jpg", 40, 40));
        Button_pasien.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        Button_pasien.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        Button_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_pasienActionPerformed(evt);
            }
        });

        btndaftar.setBackground(new java.awt.Color(105, 183, 240));
        btndaftar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndaftar.setText("Pendaftaran");
        btndaftar.setIcon(resizeIcon("/Image/pendaftaran.png", 50, 40));
        btndaftar.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        btndaftar.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        brekam.setBackground(new java.awt.Color(105, 183, 240));
        brekam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brekam.setText("Rekam Medis");
        brekam.setIcon(resizeIcon("/Image/rekam.jpg", 40, 40));
        brekam.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        brekam.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        brekam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brekamActionPerformed(evt);
            }
        });

        bresep.setBackground(new java.awt.Color(105, 183, 240));
        bresep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bresep.setText("Resep");
        bresep.setIcon(resizeIcon("/Image/resep.jpg", 60, 40));
        bresep.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        bresep.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        bresep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresepActionPerformed(evt);
            }
        });

        btnpembayaran.setBackground(new java.awt.Color(105, 183, 240));
        btnpembayaran.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpembayaran.setText("Pembayaran");
        btnpembayaran.setIcon(resizeIcon("/Image/bayar.jpg", 50, 40));
        btnpembayaran.setVerticalTextPosition(SwingConstants.BOTTOM);  // Teks di bawah ikon
        btnpembayaran.setHorizontalTextPosition(SwingConstants.CENTER); // Teks rata tengah
        btnpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpembayaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btndaftar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpoli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdokter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_obat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_pasien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bresep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brekam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpembayaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageuserdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(manageuserdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpoli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdokter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Button_obat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_pasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brekam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bresep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpembayaran)
                .addContainerGap(693, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(11, 99, 162));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout logo2Layout = new javax.swing.GroupLayout(logo2);
        logo2.setLayout(logo2Layout);
        logo2Layout.setHorizontalGroup(
            logo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        logo2Layout.setVerticalGroup(
            logo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addGap(381, 381, 381)))
                .addComponent(closeButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundlogin1Layout = new javax.swing.GroupLayout(backgroundlogin1);
        backgroundlogin1.setLayout(backgroundlogin1Layout);
        backgroundlogin1Layout.setHorizontalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundlogin1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundlogin1Layout.setVerticalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundlogin1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(backgroundlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(backgroundlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    private void btnpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpembayaranActionPerformed
        try {
            // TODO add your handling code here:
            new pembayaran() .setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnpembayaranActionPerformed

    private void bresepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresepActionPerformed
        try {
            // TODO add your handling code here:
            new Resep().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_bresepActionPerformed

    private void brekamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brekamActionPerformed
        try {
            // TODO add your handling code here:
            new rekammedis().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_brekamActionPerformed

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        // TODO add your handling code here:
        new formpendaftaran() .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndaftarActionPerformed

    private void Button_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_pasienActionPerformed
        // TODO add your handling code here:
        new formpasien() .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_pasienActionPerformed

    private void Button_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_obatActionPerformed
        new Obat().setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_Button_obatActionPerformed

    private void bdokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdokterActionPerformed
        // TODO add your handling code here:
        new formdokter().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bdokterActionPerformed

    private void btnpoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpoliActionPerformed
        // TODO add your handling code here:
        new formpoli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpoliActionPerformed

    private void manageuserdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageuserdataActionPerformed
        new ManageDataUser().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_manageuserdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
// Tambahkan animasi klik (zoom-in dan zoom-out)

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Dashboard().setVisible(true);
                
            }
        });
    }
public void setUserNip() {


        String userNip = decrypt(SessionManager.getNip()); // Ambil NIP yang sudah disimpan
        String nama = decrypt(SessionManager.getNama());

        jLabel1.setText("Halo "+ nama ); // Set teks di JLabel
        jLabel2.setText(" NIP: " + userNip);
    }
    private void setFullScreen() {
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        if (gd.isFullScreenSupported()) {
            gd.setFullScreenWindow(this); // Atur fullscreen
        } else {
            // Jika tidak didukung, gunakan ukuran layar
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            setSize(screenSize.width, screenSize.height);
            setExtendedState(JFrame.MAXIMIZED_BOTH); // Alternatif fullscreen
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_obat;
    private javax.swing.JButton Button_pasien;
    private Apps.backgrounddashboard backgroundlogin1;
    private javax.swing.JButton bdokter;
    private javax.swing.JButton brekam;
    private javax.swing.JButton bresep;
    private javax.swing.JButton btndaftar;
    private javax.swing.JButton btnpembayaran;
    private javax.swing.JButton btnpoli;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private Apps.logo logo2;
    private javax.swing.JButton manageuserdata;
    // End of variables declaration//GEN-END:variables
}
