/*
 * To change this license header, choose License Headers in Project Properties.
 * and open the template in the editor. * To change this template file, choose Tools | Templates

 */

package Apps;
import Config.KoneksiDatabase;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
/**
 *
 * @author BABY ROG
 */

 public class formpoli extends javax.swing.JFrame {
    private Connection conn = KoneksiDatabase.getConnection();
    private DefaultTableModel tabmode;
    private Connection connection;
    public formpoli polii = null;
    
    public String id;
    public String getid(){
        return id;
    }
    
         public void dokterTerpilih(){
        cariDokter1 cd = new cariDokter1();
        cd.polii = this;
        iddokter.setText(id);
    }
    
    
    private void handleWindowFocus() {
    addWindowFocusListener(new WindowFocusListener() {
        @Override
        public void windowGainedFocus(WindowEvent e) {
            // Window mendapat focus kembali
        }
        
        @Override
        public void windowLostFocus(WindowEvent e) {
            // Window kehilangan focus
        }
    });
}
    
    private void handleFormClosed() {
    SwingUtilities.invokeLater(() -> {
        // Re-enable field iddokter
        iddokter.setEnabled(true);
        
        // Kembalikan focus ke parent window tanpa mengganggu interaksi lain
        this.toFront();
        this.requestFocus();
        
        // Focus ke field id dokter
        iddokter.requestFocus();
    });
}
    
    
    public formpoli() {
    initComponents();
    datatable();
    handleWindowFocus(); // Tambahkan window focus handler
    setFullScreen();
     handleFormClosed();
    
    // Pastikan window selalu visible
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            // Handle close button dengan benar
            new Dashboard().setVisible(true);
            dispose();
        }
    });
}

    
    formpoli(String string, String string0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form formpoli
     */
    
         protected void aktif(){
    jidp.requestFocus();
}

   protected void kosong() {
    try {
        jidp.setText("");
        iddokter.setText("");
        jnp.setText("");
        cruangpoli.setSelectedIndex(0);
        jjm.setText("");
        jjs.setText("");
        jpemeriksaan.setDate(null);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error di method kosong(): " + e.getMessage());
    }
}

protected void datatable() {
    try {
        Object[] Baris = {"ID Poli", "ID Dokter", "Nama Poli", "Ruang Poli", "Tanggal Praktek", "Jam Mulai", "Jam Selesai"};
        tabmode = new DefaultTableModel(null, Baris);
        String sql = "SELECT * FROM poli ORDER BY id_poli ASC";

        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet hasil = pst.executeQuery();

        while (hasil.next()) {
            tabmode.addRow(new Object[] {
                hasil.getString("id_poli"),
                hasil.getString("id_dokter"),
                hasil.getString("nama_poli"),
                hasil.getString("ruang_poli"),
                hasil.getString("tanggal_praktek"),
                hasil.getString("jam_mulai"),
                hasil.getString("jam_selesai")
            });
        }

        table.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data:\n" + e.getMessage());
    }
}




/**
 *
 * @author USER
 */

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jidp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iddokter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jnp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cariiddok = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpemeriksaan = new com.toedter.calendar.JDateChooser();
        jjm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cruangpoli = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jjs = new javax.swing.JTextField();
        bdel = new javax.swing.JButton();
        bcan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bsave = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 197, 0, 12);
        getContentPane().add(closeButton, gridBagConstraints);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 813;
        gridBagConstraints.ipady = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(35, 135, 146, 0);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("                            DATA POLI");
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 42));

        jidp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ID POLI");

        iddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddokterActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("ID DOKTER");

        jnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("NAMA POLI");

        cariiddok.setText("Cari");
        cariiddok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariiddokActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Ruang Poli");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Tanggal Praktek");

        jjm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjmActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Jam Mulai");

        cruangpoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.1.1", "2.1.2", "2.1.3", "2.1.4" }));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Jam Selesai");

        jjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjsActionPerformed(evt);
            }
        });

        bdel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdel.setText("Delete");
        bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelActionPerformed(evt);
            }
        });

        bcan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bcan.setText("Cancel");
        bcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcanActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bsave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsave.setText("Save");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bsave)
                .addGap(40, 40, 40)
                .addComponent(bedit)
                .addGap(42, 42, 42)
                .addComponent(bcan)
                .addGap(40, 40, 40)
                .addComponent(bdel)
                .addGap(287, 287, 287))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(cruangpoli, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jidp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(cariiddok)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jjm)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jjs, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(75, 75, 75)))))
                .addGap(392, 392, 392))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cariiddok))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cruangpoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jpemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jjm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdel)
                    .addComponent(bcan)
                    .addComponent(bedit)
                    .addComponent(bsave))
                .addGap(46, 46, 46))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -171;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 180, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void jidpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidpActionPerformed

    private void jnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnpActionPerformed

    private void jjmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjmActionPerformed

    private void jjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjsActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        // TODO add your handling code here:
String sql = "INSERT INTO poli (id_poli, id_dokter, nama_poli, ruang_poli, tanggal_praktek, jam_mulai, jam_selesai) VALUES (?, ?, ?, ?, ?, ?, ?)";
try {
    PreparedStatement stat = conn.prepareStatement(sql);

    stat.setString(1, jidp.getText());
    stat.setString(2, iddokter.getText());
    stat.setString(3, jnp.getText());
    stat.setString(4, cruangpoli.getSelectedItem().toString());
    stat.setString(6, jjm.getText());
    stat.setString(7, jjs.getText());
    
    java.util.Date tgl = jpemeriksaan.getDate();
    if (tgl != null) {
        stat.setDate(5, new java.sql.Date(tgl.getTime())); // tanggal_lahir
    } else {
        stat.setNull(7, java.sql.Types.DATE);
    }

    stat.executeUpdate();
    kosong();
    jidp.requestFocus();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
}
datatable();

    }//GEN-LAST:event_bsaveActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:
try {
    String sql = "UPDATE poli SET id_poli=?, id_dokter=?, nama_poli=?, ruang_poli=?, tanggal_praktek=?, jam_mulai=?, jam_selesai=? WHERE id_poli=?";
    PreparedStatement stat = conn.prepareStatement(sql);
    
    // Parameter 1: id_poli (untuk SET)
    stat.setString(1, jidp.getText());
    
    // Parameter 2: id_dokter
    stat.setString(2, iddokter.getText());
    
    // Parameter 3: nama_poli
    stat.setString(3, jnp.getText());
    
    // Parameter 4: ruang_poli
    stat.setString(4, cruangpoli.getSelectedItem().toString());
    
    // Parameter 5: tanggal_praktek
    java.util.Date tgl = jpemeriksaan.getDate();
    if (tgl != null) {
        stat.setDate(5, new java.sql.Date(tgl.getTime()));
    } else {
        stat.setNull(5, java.sql.Types.DATE);
    }
    
    // Parameter 6: jam_mulai
    stat.setString(6, jjm.getText());
    
    // Parameter 7: jam_selesai
    stat.setString(7, jjs.getText());
    
    // Parameter 8: id_poli (untuk WHERE clause)
    stat.setString(8, jidp.getText()); // atau gunakan ID yang berbeda untuk kondisi WHERE
    
    stat.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil diubah");
    kosong();
    jidp.requestFocus();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data gagal diubah\n" + e);
}
datatable();
    }//GEN-LAST:event_beditActionPerformed

    private void bcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcanActionPerformed
        // TODO add your handling code here:
        kosong();
        
    }//GEN-LAST:event_bcanActionPerformed

    private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
        // TODO add your handling code here:
String sql = "DELETE FROM poli WHERE id_poli = ?";
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, jidp.getText());

        int rowsAffected = stat.executeUpdate();

        if (rowsAffected > 0) {
            System.out.println("Data berhasil dihapus.");
        } else {
            System.out.println("Data tidak ditemukan atau gagal dihapus.");
        }

        kosong();     // Kosongkan input
        datatable();  // Refresh tabel

    } catch (SQLException ex) {
        Logger.getLogger(formdokter.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("Gagal menghapus data: " + ex.getMessage());
    }

    }//GEN-LAST:event_bdelActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add y
        int selectedRow = table.getSelectedRow();

if (selectedRow != -1) {
    try {
        // Tanggal
        String tgl = tabmode.getValueAt(selectedRow, 4).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date tanggal = sdf.parse(tgl);
        jpemeriksaan.setDate(tanggal);

        // Form input
        jidp.setText(tabmode.getValueAt(selectedRow, 0).toString());
        iddokter.setText(tabmode.getValueAt(selectedRow, 1).toString());
        jnp.setText(tabmode.getValueAt(selectedRow, 2).toString());
        cruangpoli.setSelectedItem(tabmode.getValueAt(selectedRow, 3).toString());

        jjm.setText(tabmode.getValueAt(selectedRow, 5).toString());
        jjs.setText(tabmode.getValueAt(selectedRow, 6).toString());

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu!");
}
    }//GEN-LAST:event_tableMouseClicked

    private void combopoliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combopoliItemStateChanged

    }//GEN-LAST:event_combopoliItemStateChanged

    private void combopoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combopoliMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combopoliMouseClicked

    private void combopoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combopoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combopoliActionPerformed

    private void iddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddokterActionPerformed

    private void cariiddokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariiddokActionPerformed
       try {
        // Disable hanya field iddokter, bukan seluruh window
        iddokter.setEnabled(false);
        
        cariDokter1 cd = new cariDokter1();
        cd.polii = this;
        
        // Karena cariDokter1 adalah JFrame, gunakan pengaturan ini:
        cd.setAlwaysOnTop(true);
        cd.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Gunakan HIDE instead of DISPOSE
        
        // Set posisi di tengah parent window
        cd.setLocationRelativeTo(this);
        
        // JANGAN disable parent window - ini yang menyebabkan masalah
        // this.setEnabled(false); // <-- Hapus baris ini
        
        cd.setVisible(true);
        cd.setResizable(false);
        
        // Tambahkan window listener untuk handle ketika form ditutup
        cd.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                handleFormClosed();
            }
            
            @Override
            public void windowClosing(WindowEvent e) {
                handleFormClosed();
            }
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error membuka form pencarian dokter: " + e.getMessage());
        handleFormClosed();
    }
    }//GEN-LAST:event_cariiddokActionPerformed
    
    private void setFullScreen() {
    try {
        // Gunakan maximized state daripada full screen mode
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Alternative: gunakan full screen hanya jika benar-benar diperlukan
        /*
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        if (gd.isFullScreenSupported()) {
            // Simpan referensi untuk bisa keluar dari full screen
            gd.setFullScreenWindow(this);
        } else {
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            setSize(screenSize.width, screenSize.height);
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        */
    } catch (Exception e) {
        // Fallback ke maximized window
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(formpoli.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpoli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcan;
    private javax.swing.JButton bdel;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JButton cariiddok;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> cruangpoli;
    private javax.swing.JTextField iddokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jidp;
    private javax.swing.JTextField jjm;
    private javax.swing.JTextField jjs;
    private javax.swing.JTextField jnp;
    private com.toedter.calendar.JDateChooser jpemeriksaan;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private void Undecorated(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 }