/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apps;
import static Apps.EncryptDecrypt.decrypt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Config.KoneksiDatabase;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static javafx.css.StyleOrigin.USER;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;

public class formpasien extends javax.swing.JFrame {
    Connection conn = new KoneksiDatabase().getConnection();
    private DefaultTableModel tabmode;
    private Object rbperempuan;
    private java.util.Date date;
    private Object txtelp;
    

    public formpasien() {
        initComponents();
        setFullScreen();
        datatable();
        ttable.getTableHeader().setFont(new java.awt.Font("Times New Roman", java.awt.Font.PLAIN, 18));
    }

  protected void aktif(){
    java.util.Date date = null;
    jpasien.setDate(date);
    txtid.requestFocus();
}

    protected void kosong(){
     jpasien.setDate(date);
     txtid.setText("");
     txtnmpasien.setText("");
     txtnik.setText("");
     txtbpjs.setText("");
     txttelp.setText("");
     txtalamat.setText("");
     bjekel.clearSelection();
    }


protected void datatable() {
    Object[] Baris = {
        "ID Pasien", "Nama", "NIK", "No.BPJS",
        "Jenis Kelamin", "Tgl. lahir", "No. Telepon", "Alamat"
    };
    tabmode = new DefaultTableModel(null, Baris);

    String sql = "SELECT * FROM pasien ORDER BY id_pasien ASC";

    try (PreparedStatement pst = conn.prepareStatement(sql)) {
        try (ResultSet hasil = pst.executeQuery()) {
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString("id_pasien"),
                    hasil.getString("nama_pasien"),
                    hasil.getString("nik"),
                    hasil.getString("no_bpjs"),
                    hasil.getString("jenis_kelamin"),
                    hasil.getString("tanggal_lahir"),
                    hasil.getString("no_telepon"),
                    hasil.getString("alamat")
                });
            }
        }
        ttable.setModel(tabmode); // update tabelnya
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bjekel = new javax.swing.ButtonGroup();
        tpasien = new javax.swing.JScrollPane();
        ttable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnmpasien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbpjs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jpasien = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txttelp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bprint = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tpasien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ttable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttableMouseClicked(evt);
            }
        });
        tpasien.setViewportView(ttable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1102;
        gridBagConstraints.ipady = 123;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 62, 0, 0);
        getContentPane().add(tpasien, gridBagConstraints);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 56, 0, 0);
        getContentPane().add(closeButton, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ID Pasien");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nama Pasien");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("NIK");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("No. BPJS");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        bjekel.add(rblaki);
        rblaki.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rblaki.setText("Laki-Laki");

        bjekel.add(rperempuan);
        rperempuan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rperempuan.setText("Perempuan");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Tgl. Lahir");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("No. Telp");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Alamat");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PASIEN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bprint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bprint.setText("CETAK DATA PASIEN");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        btbatal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btbatal.setText("BATAL");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        bthapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bthapus.setText("HAPUS");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btubah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btubah.setText("UBAH");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        btsimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(145, 145, 145))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btsimpan)
                        .addGap(61, 61, 61)
                        .addComponent(btubah)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtbpjs)
                                .addComponent(txtnik)
                                .addComponent(txtnmpasien)
                                .addComponent(txtid)
                                .addComponent(txttelp, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addComponent(rblaki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65)
                                            .addComponent(rperempuan)))
                                    .addGap(19, 19, 19)))
                            .addComponent(jpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(bthapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btbatal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(bprint)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnmpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbpjs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rblaki)
                        .addComponent(rperempuan)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttelp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthapus)
                    .addComponent(btubah)
                    .addComponent(btsimpan)
                    .addComponent(btbatal)
                    .addComponent(bprint))
                .addGap(2, 2, 2))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 72;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 192, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
String sql = "INSERT INTO pasien (id_pasien, nama_pasien, nik, no_bpjs, jenis_kelamin, tanggal_lahir, no_telepon, alamat) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
try {
    PreparedStatement stat = conn.prepareStatement(sql);

    stat.setString(1, txtid.getText());
    stat.setString(2, txtnmpasien.getText());
    stat.setString(3, txtnik.getText());
    stat.setString(4, txtbpjs.getText());

    String bjekel = "";
    if (rblaki.isSelected()) {
        bjekel = "Laki-laki";
    } else if (rperempuan.isSelected()) {
        bjekel = "Perempuan";
    }
    stat.setString(5, bjekel); // jenis_kelamin

    java.util.Date tgl = jpasien.getDate();
    if (tgl != null) {
        stat.setDate(6, new java.sql.Date(tgl.getTime())); // tanggal_lahir
    } else {
        stat.setNull(6, java.sql.Types.DATE);
    }

    stat.setString(7, txttelp.getText());   // no_telepon
    stat.setString(8, txtalamat.getText()); // alamat

    stat.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    kosong();
    txtid.requestFocus();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
}
datatable();

    }//GEN-LAST:event_btsimpanActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        // TODO add your handling code here:
String bjekel = "";
if (rblaki.isSelected()) {
    bjekel = "Laki-laki";
} else if (rperempuan.isSelected()) {
    bjekel = "Perempuan";
}

try {
    String sql = "UPDATE pasien SET nama_pasien=?, nik=?, no_bpjs=?, tanggal_lahir=?, jenis_kelamin=?, no_telepon=?, alamat=? WHERE id_pasien=?";
    PreparedStatement stat = conn.prepareStatement(sql);

    stat.setString(1, txtnmpasien.getText());    // nama_pasien
    stat.setString(2, txtnik.getText());         // nik
    stat.setString(3, txtbpjs.getText());        // no_bpjs

    // Tanggal lahir (posisi ke-5)
    java.util.Date tgl = jpasien.getDate();      
    if (tgl != null) {
        stat.setDate(4, new java.sql.Date(tgl.getTime()));
    } else {
        stat.setNull(4, java.sql.Types.DATE);
    }

    stat.setString(5, bjekel);                   // jenis_kelamin
    stat.setString(6, txttelp.getText());        // no_telepon
    stat.setString(7, txtalamat.getText());      // alamat
    stat.setString(8, txtid.getText());          // WHERE id_pasien = ?

    stat.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data berhasil diubah");
    kosong();
    txtid.requestFocus();
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data gagal diubah\n" + e);
}
datatable();


    }//GEN-LAST:event_btubahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
       String idText = txtid.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Konfirmasi hapus dengan user
    int konfirmasi = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin menghapus data dengan ID: " + idText + "?", 
        "Konfirmasi Hapus", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // Query DELETE yang benar - pastikan nama tabel dan kolom sesuai
            String sql = "DELETE FROM pasien WHERE id_pasien=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            // Set parameter dengan tipe data yang sesuai (int jika ID bertipe integer)
            stat.setInt(1, Integer.parseInt(idText));
            
            // Eksekusi query dan periksa hasilnya
            int rowsAffected = stat.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                
                // Clear form input
                txtid.setText("");
                // Clear field lain jika ada (contoh):
                // txtnama.setText("");
                // txtalamat.setText("");
                
                // Refresh tampilan data
                datatable();
                kosong();
                
            } else {
                JOptionPane.showMessageDialog(this, "Data dengan ID tersebut tidak ditemukan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
}
    }//GEN-LAST:event_bthapusActionPerformed
    }
    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
         kosong();
       datatable(); 
    }//GEN-LAST:event_btbatalActionPerformed

   
    
    private void ttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttableMouseClicked
// TODO add your handling code here:  
int selectedRow = ttable.getSelectedRow();

if (selectedRow != -1) {
    try {
        // Tanggal
        String tgl = tabmode.getValueAt(selectedRow, 5).toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date tanggal = sdf.parse(tgl);
        jpasien.setDate(tanggal);

        // Form input
        txtid.setText(tabmode.getValueAt(selectedRow, 0).toString());
        txtnmpasien.setText(tabmode.getValueAt(selectedRow, 1).toString());
        txtnik.setText(tabmode.getValueAt(selectedRow, 2).toString());
        txtbpjs.setText(tabmode.getValueAt(selectedRow, 3).toString());

        // Jenis kelamin
        String bjekel = tabmode.getValueAt(selectedRow, 4).toString();
        if (bjekel.equalsIgnoreCase("Laki-laki")) {
            rblaki.setSelected(true);
        } else {
            rperempuan.setSelected(true);
        }

        // Telepon
        Object telpObj = tabmode.getValueAt(selectedRow, 6);
        txttelp.setText(telpObj != null ? telpObj.toString() : "");

        // Alamat
        txtalamat.setText(tabmode.getValueAt(selectedRow, 7).toString());

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu!");
}



    
                  
    }//GEN-LAST:event_ttableMouseClicked

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        // TODO add your handling code here:
         try {
            String reportPath = "src/laporan/laporan_pasien.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
            HashMap<String, Object> parameters = new HashMap<>();

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(jasperPrint, false);

            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, "Error JasperReports: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpasien().setVisible(true);
            }
        });
    }
       private void setFullScreen() {
// Menggunakan ukuran layar penuh tanpa mode fullscreen
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
setSize(screenSize.width, screenSize.height);
setExtendedState(JFrame.MAXIMIZED_BOTH); // Alternatif fullscreen tanpa mengubah mode penuh

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bjekel;
    private javax.swing.JButton bprint;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btubah;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jpasien;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JScrollPane tpasien;
    private javax.swing.JTable ttable;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtbpjs;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnmpasien;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables
}