/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import Config.KoneksiDatabase;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class formpendaftaran extends javax.swing.JFrame {
    Connection conn = new KoneksiDatabase().getConnection();
    private DefaultTableModel tabmode;
    private Object status_perawatan;
    
    public formpendaftaran daftar = null;
    
    public String id;
    public String getid(){
        return id;
    }
    public String npoli;
    public String getnpoli(){
        return npoli;
    }
    
    public String idpas;
    
         public void dokterTerpilih(){
        cariDokter1 cd = new cariDokter1();
        cd.daftar = this;
        iddokter.setText(id);
        poli.setText(npoli);
    }
         
         public void pasienTerpilih(){
        cariPasien cp = new cariPasien();
        cp.daftar = this;
        idpasien.setText(idpas);
        daftar.setVisible(true);
    }
         
         
         



    /**
     * Creates new form formpendaftaran
     */
    public formpendaftaran() {
        initComponents();
        datatable();
        setFullScreen();
    }
    
    protected void aktif(){
iddaftar.requestFocus();
}

protected void kosong() {
    iddaftar.setText("");         // Mengosongkan JTextField untuk ID Daftar
    idpasien.setText("");         // Mengosongkan JTextField untuk ID Pasien
    iddokter.setText("");         // Mengosongkan JTextField untuk ID Dokter
    poli.setText("");             // Mengosongkan JTextField untuk Poli
    cperawatan.setSelectedItem(null); // Jika cperawatan adalah JComboBox
    statuss.setText("");          // Mengosongkan JTextField untuk Status
    tglkunjungan.setDate(null);   // Mengosongkan tanggal pada JDateChooser (JCalendar)
}

protected void datatable() {
    // Header kolom tabel (jumlah = 9)
    Object[] Baris = {
        "ID Daftar", "ID Pasien", "ID Dokter", "Poli", "Tanggal Kunjungan","Status Perawatan", 
        "Status"
    };

    // Buat model tabel dengan kolom yang sesuai
    tabmode = new DefaultTableModel(null, Baris);

    // Ambil keyword pencarian dari text field

    try {
        // Query SQL dengan pencarian berdasarkan ID atau nama pasien
        String sql = "select * from pendaftaran_pasien";

        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        // Loop data dari hasil query
        while (hasil.next()) {
            tabmode.addRow(new Object[] {
                hasil.getString("id_pendaftaran"),
                hasil.getString("id_pasien"),
                hasil.getString("id_dokter"),
                hasil.getString("poli"),
                hasil.getString("tanggal_kunjungan"),
                hasil.getString("status_perawatan"),
                hasil.getString("status"),
                
            });
        }

        // Tampilkan data ke tabel
        tabeldaftar.setModel(tabmode);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldaftar = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iddaftar = new javax.swing.JTextField();
        idpasien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cariidpasien = new javax.swing.JButton();
        cariiddok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        iddokter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        poli = new javax.swing.JTextField();
        tglkunjungan = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cperawatan = new javax.swing.JComboBox<>();
        statuss = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        dtnsimpan = new javax.swing.JButton();
        dtnhapus = new javax.swing.JButton();
        dtnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tabeldaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldaftarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldaftar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 706;
        gridBagConstraints.ipady = 153;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(65, 156, 13, 0);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 158, 0, 12);
        getContentPane().add(closeButton, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("FORMULIR PENDAFTARAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ID PENDAFTARAN");

        idpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpasienActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ID PASIEN ");

        cariidpasien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cariidpasien.setText("Cari");
        cariidpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariidpasienActionPerformed(evt);
            }
        });

        cariiddok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cariiddok.setText("Cari");
        cariiddok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariiddokActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID DOKTER ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("POLI");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("TANGGAL KUNJUNGAN ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("STATUS PERAWATAN");

        cperawatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RAWAT JALAN", "RAWAT INAP" }));

        statuss.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        statuss.setText("STATUS");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELESAI", "MENUNGGU", " ", " " }));

        dtnsimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dtnsimpan.setText("SIMPAN");
        dtnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtnsimpanActionPerformed(evt);
            }
        });

        dtnhapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dtnhapus.setText("HAPUS");
        dtnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtnhapusActionPerformed(evt);
            }
        });

        dtnbatal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dtnbatal.setText("BATAL");
        dtnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtnbatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tglkunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(poli, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(181, 181, 181))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iddaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cariidpasien))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cariiddok)))
                                .addGap(128, 128, 128))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statuss))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cperawatan, 0, 217, Short.MAX_VALUE)
                                        .addGap(297, 297, 297))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(dtnsimpan)
                .addGap(70, 70, 70)
                .addComponent(dtnhapus)
                .addGap(78, 78, 78)
                .addComponent(dtnbatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(220, 220, 220))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iddaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cariidpasien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cariiddok)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(poli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(tglkunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cperawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statuss)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtnsimpan)
                    .addComponent(dtnhapus)
                    .addComponent(dtnbatal))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(24, 156, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpasienActionPerformed

    private void dtnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtnsimpanActionPerformed
        // TODO add your handling code here:
String sql = "INSERT INTO pendaftaran_pasien (id_pendaftaran, id_pasien, id_dokter, poli, tanggal_kunjungan, status_perawatan, status) VALUES (?, ?, ?, ?, ?, ?, ?)";
try {
    PreparedStatement stat = conn.prepareStatement(sql);

    java.util.Date date = tglkunjungan.getDate();
    java.sql.Date sqlDate = null;
    if (date != null) {
        sqlDate = new java.sql.Date(date.getTime());
    }

    stat.setString(1, iddaftar.getText());
    stat.setString(2, idpasien.getText());
    stat.setString(3, iddokter.getText());
    stat.setString(4, poli.getText());

    if (sqlDate != null) {
        stat.setDate(5, sqlDate);
    } else {
        stat.setNull(5, java.sql.Types.DATE);
    }

    String cperawatanSelected = cperawatan.getSelectedItem() != null ? cperawatan.getSelectedItem().toString() : "";
    stat.setString(6, cperawatanSelected);

    String statusSelected = status.getSelectedItem() != null ? status.getSelectedItem().toString() : "";
    stat.setString(7, statusSelected);

    stat.executeUpdate();
    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    kosong();
    iddaftar.requestFocus();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
}

datatable();


    }//GEN-LAST:event_dtnsimpanActionPerformed

    private void dtnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtnhapusActionPerformed
        // TODO add your handling code here:
              String idText = iddaftar.getText().trim();
    if (idText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Konfirmasi hapus dengan user
    int konfirmasi = JOptionPane.showConfirmDialog(
        this, 
        "Apakah Anda yakin ingin menghapus data dengan ID: " + idText + "?", 
        "Konfirmasi Hapus", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            // Query DELETE yang benar - pastikan nama tabel dan kolom sesuai
            String sql = "DELETE FROM pendaftaran_pasien WHERE id_pendaftaran=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            // Set parameter dengan tipe data yang sesuai (int jika ID bertipe integer)
            stat.setInt(1, Integer.parseInt(idText));
            
            // Eksekusi query dan periksa hasilnya
            int rowsAffected = stat.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                
                // Clear form input
                iddaftar.setText("");
                // Clear field lain jika ada (contoh):
                // txtnama.setText("");
                // txtalamat.setText("");
                
                // Refresh tampilan data
                datatable();
                kosong();
                
            } else {
                JOptionPane.showMessageDialog(this, "Data dengan ID tersebut tidak ditemukan!", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        }
    }
    }//GEN-LAST:event_dtnhapusActionPerformed

    private void tabeldaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldaftarMouseClicked
        // TODO add your handling code here:
try {
    int bar = tabeldaftar.getSelectedRow();
    if (bar == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu dari tabel.");
        return;
    }

    iddaftar.setText(tabmode.getValueAt(bar, 0).toString());
    idpasien.setText(tabmode.getValueAt(bar, 1).toString());
    iddokter.setText(tabmode.getValueAt(bar, 2).toString());
    poli.setText(tabmode.getValueAt(bar, 3).toString());

    Object cPerawatanObj = tabmode.getValueAt(bar, 5);
    if (cPerawatanObj != null) {
        cperawatan.setSelectedItem(cPerawatanObj.toString());
    } else {
        cperawatan.setSelectedIndex(-1);
    }

    Object statusObj = tabmode.getValueAt(bar, 6);
    if (statusObj != null) {
        status.setSelectedItem(statusObj.toString());
    } else {
        status.setSelectedIndex(-1);
    }

    // Kalau tanggal di kolom 5 atau 6 belum jelas, coba cek dan sesuaikan
    // Misal tanggal di kolom 5, kita ubah menjadi:
    Object objTanggal = tabmode.getValueAt(bar, 4); // atau 6 kalau di situ
    if (objTanggal != null) {
        String tgldaftar = objTanggal.toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date tanggal = sdf.parse(tgldaftar);
        tglkunjungan.setDate(tanggal);
    } else {
        tglkunjungan.setDate(null);
    }

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
}


    }//GEN-LAST:event_tabeldaftarMouseClicked

    private void dtnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtnbatalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_dtnbatalActionPerformed

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void cariiddokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariiddokActionPerformed
        // TODO add your handling code here:
       try {
        // Disable hanya field iddokter, bukan seluruh window
        iddokter.setEnabled(false);
        poli.setEnabled(false);
        
        cariDokter1 cd = new cariDokter1();
        cd.daftar = this;
        
        // Karena cariDokter1 adalah JFrame, gunakan pengaturan ini:
        cd.setAlwaysOnTop(true);
        cd.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Gunakan HIDE instead of DISPOSE
        
        // Set posisi di tengah parent window
        cd.setLocationRelativeTo(this);
        
        // JANGAN disable parent window - ini yang menyebabkan masalah
        // this.setEnabled(false); // <-- Hapus baris ini
        
        cd.setVisible(true);
        cd.setResizable(false);
        
        // Tambahkan window listener untuk handle ketika form ditutup
        cd.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                handleFormClosed();
            }
            
            @Override
            public void windowClosing(WindowEvent e) {
                handleFormClosed();
            }

            private void handleFormClosed() {
                this.setVisible(false);//To change body of generated methods, choose Tools | Templates.
            }

            private void setVisible(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error membuka form pencarian dokter: " + e.getMessage());
        handleFormClosed();
    }

    }//GEN-LAST:event_cariiddokActionPerformed

    private void cariidpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariidpasienActionPerformed
        // TODO add your handling code here:
      try {
        // Disable hanya field iddokter, bukan seluruh window
        idpasien.setEnabled(false);
        
        cariPasien cp = new cariPasien();
        cp.daftar = this;
        
        // Karena cariDokter1 adalah JFrame, gunakan pengaturan ini:
        cp.setAlwaysOnTop(true);
        cp.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Gunakan HIDE instead of DISPOSE
        
        // Set posisi di tengah parent window
        cp.setLocationRelativeTo(this);
        
        // JANGAN disable parent window - ini yang menyebabkan masalah
        // this.setEnabled(false); // <-- Hapus baris ini
        
        cp.setVisible(true);
        cp.setResizable(false);
        
        // Tambahkan window listener untuk handle ketika form ditutup
        cp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                handleFormClosed();
            }
            
            @Override
            public void windowClosing(WindowEvent e) {
                handleFormClosed();
            }

            private void handleFormClosed() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error membuka form pencarian dokter: " + e.getMessage());
        handleFormClosed();
    }
    }//GEN-LAST:event_cariidpasienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpendaftaran().setVisible(true);
            }
        });
    }
    
           private void setFullScreen() {
// Menggunakan ukuran layar penuh tanpa mode fullscreen
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
setSize(screenSize.width, screenSize.height);
setExtendedState(JFrame.MAXIMIZED_BOTH); // Alternatif fullscreen tanpa mengubah mode penuh

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariiddok;
    private javax.swing.JButton cariidpasien;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> cperawatan;
    private javax.swing.JButton dtnbatal;
    private javax.swing.JButton dtnhapus;
    private javax.swing.JButton dtnsimpan;
    private javax.swing.JTextField iddaftar;
    private javax.swing.JTextField iddokter;
    private javax.swing.JTextField idpasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField poli;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel statuss;
    private javax.swing.JTable tabeldaftar;
    private com.toedter.calendar.JDateChooser tglkunjungan;
    // End of variables declaration//GEN-END:variables

    private void handleFormClosed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
