/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;

import static Apps.EncryptDecrypt.decrypt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Config.KoneksiDatabase;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import static javafx.css.StyleOrigin.USER;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.SwingUtilities;

/**
 *
 * @author USER
 */
public class formdokter extends javax.swing.JFrame {
    private Connection conn = KoneksiDatabase.getConnection();
    private DefaultTableModel tabmode;
    private Object dialog;
    private Connection connection;
    formdokter(String string, String string0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form formdokter
     */
    
         protected void aktif(){
    jiddok.requestFocus();
}

   protected void kosong() {
    try {
        jiddok.setText("");
        jnamadok.setText("");
        cpoli.setSelectedIndex(0);
        jbiaya.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error di method kosong(): " + e.getMessage());
    }
}

protected void datatable() {
    try {
        Object[] Baris = {"ID Dokter", "Nama Dokter", "Poli", "Biaya Dokter"};
        tabmode = new DefaultTableModel(null, Baris);
        String sql = "SELECT * FROM dokter ORDER BY id_dokter ASC";

        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet hasil = pst.executeQuery();

        while (hasil.next()) {
            tabmode.addRow(new Object[] {
                hasil.getString("id_dokter"),
                hasil.getString("nama_dokter"),
                hasil.getString("poli"),
                hasil.getString("biaya")
            });
        }

        ttable.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data:\n" + e.getMessage());
    }
}


    public formdokter() {
        initComponents();
        datatable();
        setFullScreen();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jiddok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jnamadok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpoli = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jbiaya = new javax.swing.JTextField();
        bcetak = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtcaridok = new javax.swing.JTextField();
        bcaridok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btsimpan = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ttable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 673;
        gridBagConstraints.ipady = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(44, 12, 0, 0);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jPanel1.setAlignmentX(1.0F);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA DOKTER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.insets = new java.awt.Insets(20, 12, 0, 68);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID DOKTER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 34, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jiddok.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 82, 0, 0);
        jPanel1.add(jiddok, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("NAMA DOKTER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 34, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 82, 0, 0);
        jPanel1.add(jnamadok, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("POLI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 34, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        cpoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BEDAH", "SARAF", "JANTUNG", "UMUM", "GIGI" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 82, 0, 0);
        jPanel1.add(cpoli, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("BIAYA ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 34, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbiayaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 186;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 82, 0, 0);
        jPanel1.add(jbiaya, gridBagConstraints);

        bcetak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bcetak.setText("Cetak Data Dokter");
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 24, 0, 0);
        jPanel1.add(bcetak, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Cari Data Dokter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 34, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        txtcaridok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaridokKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 29, 0, 0);
        jPanel1.add(txtcaridok, gridBagConstraints);

        bcaridok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bcaridok.setText("Cari");
        bcaridok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaridokActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 0, 0);
        jPanel1.add(bcaridok, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("UBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 3, 0, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 13, 0, 0);
        jPanel1.add(jButton2, gridBagConstraints);

        btbatal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btbatal.setText("BATAL");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 18, 0, 0);
        jPanel1.add(btbatal, gridBagConstraints);

        btsimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btsimpan.setText("SIMPAN");
        btsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsimpanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 49, 0, 0);
        jPanel1.add(btsimpan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(closeButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaridokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaridokKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcaridokKeyPressed

    private void bcaridokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaridokActionPerformed
        // TODO add your handling code here
    String[] Baris = {"ID DOKTER", "NAMA DOKTER", "POLI", "BIAYA"};
    tabmode = new DefaultTableModel(null, Baris);
    ttable.setModel(tabmode);
    String sql = "SELECT * FROM dokter WHERE id_dokter LIKE '%" + txtcaridok.getText() + "%' OR nama_dokter LIKE '%" + txtcaridok.getText() + "%'";
    
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            String a = hasil.getString("id_dokter");
            String b = hasil.getString("nama_dokter");
            String c = hasil.getString("poli");
            String d = hasil.getString("biaya");
            
            String[] data = {a, b, c, d};
            tabmode.addRow(data);
        }
    } catch (Exception e) {
        System.out.println("Error saat mencari data: " + e);
    }
    }//GEN-LAST:event_bcaridokActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_btbatalActionPerformed

    private void btsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsimpanActionPerformed
        // TODO add your handling code here:
        String sql ="insert into dokter values (?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, jiddok.getText());
            stat.setString(2, jnamadok.getText());
            stat.setString(3, cpoli.getSelectedItem().toString());
            stat.setString(4, jbiaya.getText());
            
            
            stat.executeUpdate();
            kosong();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }

    }//GEN-LAST:event_btsimpanActionPerformed

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void ttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttableMouseClicked
        // TODO add your handling code here:
int selectedRow = ttable.getSelectedRow();

if (selectedRow != -1) {
    try {
        // Set data dari tabel ke input form sesuai urutan kolom baru
        jiddok.setText(tabmode.getValueAt(selectedRow, 0).toString());        
        jnamadok.setText(tabmode.getValueAt(selectedRow, 1).toString()); 
        cpoli.setSelectedItem(tabmode.getValueAt(selectedRow, 2).toString()); // gunakan setSelectedItem, bukan setSelected
        jbiaya.setText(tabmode.getValueAt(selectedRow, 3).toString()); 

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
} else {
    JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu!");
}

    }//GEN-LAST:event_ttableMouseClicked

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        // TODO add your handling code here:
         try {
            String reportPath = "src/laporan/laporan_dokter.jrxml";
            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
            HashMap<String, Object> parameters = new HashMap<>();

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(jasperPrint, false);

            } catch (JRException e) {
                JOptionPane.showMessageDialog(null, "Error JasperReports: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), 
                                            "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bcetakActionPerformed

    private void jbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbiayaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String sql = "UPDATE dokter SET id_dokter=?, nama_dokter=?, poli=?, biaya=? WHERE id_dokter=?";
try {
    PreparedStatement stat = conn.prepareStatement(sql);

    stat.setString(1, jiddok.getText());                       // SET id_dokter baru
    stat.setString(2, jnamadok.getText());                    // SET nama_dokter
    stat.setString(3, cpoli.getSelectedItem().toString());    // SET poli
    stat.setString(4, jbiaya.getText());                      // SET biaya
    stat.setString(5, jiddok.getText());                      // WHERE id_dokter = ?

    stat.executeUpdate();

    kosong();
    jiddok.requestFocus();
    datatable();


} catch (SQLException ex) {
    Logger.getLogger(formdokter.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + ex.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String sql = "DELETE FROM dokter WHERE id_dokter = ?";
    try {
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, jiddok.getText());

        int rowsAffected = stat.executeUpdate();

        if (rowsAffected > 0) {
            System.out.println("Data berhasil dihapus.");
        } else {
            System.out.println("Data tidak ditemukan atau gagal dihapus.");
        }

        kosong();     // Kosongkan input
        datatable();  // Refresh tabel

    } catch (SQLException ex) {
        Logger.getLogger(formdokter.class.getName()).log(Level.SEVERE, null, ex);
        System.out.println("Gagal menghapus data: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formdokter().setVisible(true);
            }
        });
    }
    private void setFullScreen() {
        // Gunakan maximized state daripada full screen mode
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Alternative: gunakan full screen hanya jika benar-benar diperlukan
        /*
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        if (gd.isFullScreenSupported()) {
            // Simpan referensi untuk bisa keluar dari full screen
            gd.setFullScreenWindow(this);
        } else {
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            setSize(screenSize.width, screenSize.height);
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        */
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcaridok;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> cpoli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jbiaya;
    private javax.swing.JTextField jiddok;
    private javax.swing.JTextField jnamadok;
    private javax.swing.JTable ttable;
    private javax.swing.JTextField txtcaridok;
    // End of variables declaration//GEN-END:variables

    void dokterTerpilih() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}