/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apps;
import Config.KoneksiDatabase;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
/**
 *
 * @author Acer
 */
public class ManageDataUser extends javax.swing.JFrame {
  private JFrame frame;
    /**
     * Creates new form ManageDataUser
     */
    public ManageDataUser() {
        initComponents();
        
        loadData();
        setFullScreen();
        setLocationRelativeTo(null);


    }
// Fungsi untuk mengisi JTable dengan data dari database
private void loadData() {
    // Logika untuk memuat ulang data tabel dari database
    // Misalnya dengan memanggil query SELECT untuk mengambil data terbaru
    try (Connection conn = KoneksiDatabase.getConnection()) {
        String sql = "SELECT nip, nama, email, status_akun FROM user";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        // Kosongkan tabel sebelum mengisinya dengan data terbaru
        DefaultTableModel model = (DefaultTableModel) tblPegawai.getModel();
        model.setRowCount(0); // Clear existing data

        // Isi tabel dengan data terbaru
        while (rs.next()) {
            Vector<Object> row = new Vector<>();
            row.add(rs.getString("nip"));
            row.add(rs.getString("nama"));
            row.add(rs.getString("email"));
            row.add(rs.getString("status_akun"));
            row.add("Activated / Deactivated");  // Button Action
            model.addRow(row);
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    private void reloadPage() {
        new ManageDataUser().setVisible(true);
        this.dispose();
        JLabel label = new JLabel("Page has been reloaded!", JLabel.CENTER);
    }

// Fungsi untuk memperbarui status akun, lalu me-reload button di kolom Action setelah perubahan
private void updateStatusAkun(String nip, String newStatus) {
    // Menampilkan pop-up konfirmasi
    int response = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin mengubah status akun menjadi "+newStatus+"?",
            "Konfirmasi Perubahan Status",
            JOptionPane.YES_NO_OPTION
    );

    if (response == JOptionPane.YES_OPTION) {
        // Jika pengguna memilih YES, lanjutkan dengan update status akun
        try (Connection conn = KoneksiDatabase.getConnection()) {
            String sql = "UPDATE user SET status_akun = ? WHERE nip = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, newStatus);
            stmt.setString(2, nip);

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                loadData();  // Memuat ulang data setelah update
                JOptionPane.showMessageDialog(this, "Berhasil memperbarui Status Akun!");
                reloadPage();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    } else {
        // Jika pengguna memilih NO, tidak ada perubahan yang dilakukan
        JOptionPane.showMessageDialog(this, "Perubahan status dibatalkan.");
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPegawai = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ManajemenUser");
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manajemen Data Pengguna");

        tblPegawai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblPegawai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Jenis Kelamin", "Status Akun", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPegawai.setRowHeight(30);
        tblPegawai.getTableHeader().setReorderingAllowed(false);
        // Menambahkan listener untuk action button
        tblPegawai.getColumn("Action").setCellRenderer(new ButtonRenderer());
        tblPegawai.getColumn("Action").setCellEditor(new ButtonEditor(new JCheckBox()));
        jScrollPane2.setViewportView(tblPegawai);
        if (tblPegawai.getColumnModel().getColumnCount() > 0) {
            tblPegawai.getColumnModel().getColumn(0).setResizable(false);
            tblPegawai.getColumnModel().getColumn(1).setResizable(false);
            tblPegawai.getColumnModel().getColumn(2).setResizable(false);
            tblPegawai.getColumnModel().getColumn(3).setResizable(false);
            tblPegawai.getColumnModel().getColumn(4).setResizable(false);
        }

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CloseButton.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                closeButtonMouseMoved(evt);
            }
        });
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton))
                .addGap(235, 235, 235)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
  new Dashboard().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered

    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked

    }//GEN-LAST:event_closeButtonMouseClicked

    private void closeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDataUser().setVisible(true);
            }
        });
    }
public class ButtonRenderer extends JButton implements TableCellRenderer {
    public ButtonRenderer() {
        setOpaque(true);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        // Dapatkan nilai status akun untuk menentukan label button
        String statusAkun = (String) table.getValueAt(row, 3);  // Kolom status_akun
        String actionButton = (statusAkun.equals("Activated")) ? "Deactivated" : "Activated";
        
        setText(actionButton);  // Set label tombol sesuai dengan status akun
        return this;
    }
}

public class ButtonEditor extends DefaultCellEditor {
    protected JButton button;
    private String label;
    private int row;

    public ButtonEditor(JCheckBox checkBox) {
        super(checkBox);
        button = new JButton();
        button.setOpaque(true);

        // Action listener untuk tombol
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Ambil data pada baris yang dipilih
                row = tblPegawai.getSelectedRow();
                String nip = (String) tblPegawai.getValueAt(row, 0);  // Kolom NIP
                String status = (String) tblPegawai.getValueAt(row, 3); // Kolom status_akun

                // Update status akun berdasarkan tombol yang diklik
                if (label.equals("Activated")) {
                    updateStatusAkun(nip, "Activated");
                } else if (label.equals("Deactivated")) {
                    updateStatusAkun(nip, "Deactivated");
                }



                button.setText(label);  // Atur label button sesuai status akun
                // After updating the status, update the button in the selected row to reflect the change
                DefaultTableModel model = (DefaultTableModel) tblPegawai.getModel();
                model.setValueAt(label, row, 4); // Update button text in Action column

                // Pindahkan fokus ke kolom NIP setelah tombol diklik
                tblPegawai.changeSelection(row, 0, false, false);  // Memindahkan fokus ke kolom NIP (kolom 0)
                
                // Trigger a refresh of the cell in the Action column
                model.fireTableCellUpdated(row, 4);  // Update kolom Action untuk menunjukkan perubahan
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
        String statusAkun = (String) table.getValueAt(row, 3);  // Ambil status akun dari kolom ke-3 (index 3)

        // Tentukan label button berdasarkan status akun
        if (statusAkun.equals("Activated")) {
            label = "Deactivated";  // Jika status akun activated, button tampil Deactivate
        } else if (statusAkun.equals("Deactivated")) {
            label = "Activated";    // Jika status akun deactivated, button tampil Activate
        }

        button.setText(label);  // Atur label button sesuai status akun
        return button;
    }
}

   private void setFullScreen() {
// Menggunakan ukuran layar penuh tanpa mode fullscreen
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
setSize(screenSize.width, screenSize.height);
setExtendedState(JFrame.MAXIMIZED_BOTH); // Alternatif fullscreen tanpa mengubah mode penuh

    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPegawai;
    // End of variables declaration//GEN-END:variables
}
